---
local_admin_user: administrator
local_admin_pass: Ansiblem@nage
adds_admin_user: serviceaccount
adds_admin_pass: password
adds_fqdn: ttlab.local
adds_ou_path: "OU=WS2016,OU=Session Hosts,OU=Citrix,DC=ttlab,DC=local"
appinstall_path: \\CTXMDT01.ttlab.local\mdt$\applications
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_user: "{{ local_admin_user }}"
ansible_password: "{{ local_admin_pass }}"
ansible_become_user: "{{ adds_admin_user }}"
ansible_become_password: "{{ adds_admin_pass }}"
