
- name: MS Office 365 business x64
  win_shell: cmd /c "$env:appinstall\Microsoft Office 365 Business x64\Install-MSOffice365_Bus_x64.cmd"
  args:
    creates: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE

- name: MS Teams X64
  win_shell: cmd /c "$env:appinstall\Microsoft Teams\install-MSTeams_x64.CMD"
  ignore_errors: yes
  args:
    creates: C:\Program Files (x86)\Microsoft\Teams\current\Teams.exe

- name: Google Chrome
  win_shell: cmd /c "$env:appinstall\Google Chrome Enterprise\install-GoogleChrome.CMD"
  ignore_errors: yes
  args:
    creates: C:\Program Files\Google\Chrome\Application\chrome.exe
  
- name: Adobe Reader
  win_shell: cmd /c "$env:appinstall\Adobe Reader DC\install-AdobeReaderDC.CMD"
  ignore_errors: yes
  args:
    creates: C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
  
- name: enable windows photo viewer
  win_shell: cmd /c "$env:appinstall\Microsoft Photo Viewer\install-microsoftphotoviewer.cmd"

- name: Onedrive
  win_shell: cmd /c "$env:appinstall\Microsoft onedrive\install-onedrive.CMD"
  become: yes
  args:
    creates: C:\Program Files (x86)\Microsoft OneDrive\OneDrive.exe
  
- name: Install notepad-plus-plus
  win_shell: cmd /c "$env:appinstall\Notepad++ 7.x\Install-Notepad.cmd"
  args:
    creates: C:\Program Files\Notepad++\notepad++.exe
