
- name: MS Office 365 business x64
  win_shell: cmd /c "$env:appinstall\Microsoft Office 365 Business x64\Install-MSOffice365_Bus_x64.cmd"
  args:
    creates: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE

- name: MS Teams X64
  win_shell: cmd /c "$env:appinstall\Microsoft Teams\install-MSTeams_x64.CMD"
  ignore_errors: yes
  args:
    creates: C:\Program Files (x86)\Microsoft\Teams\current\Teams.exe

- name: Google Chrome
  win_shell: cmd /c "$env:appinstall\Google Chrome Enterprise\install-GoogleChrome.CMD"
  ignore_errors: yes

- name: Adobe Reader
  win_shell: cmd /c "$env:appinstall\Adobe Reader DC\install-AdobeReaderDC.CMD"
  ignore_errors: yes
  
#- name: Install notepad-plus-plus
#  win_package:
#    path: https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.x64.exe
#    product_id: Notepad++
#    arguments: /S
#    state: present
