# module ref: https://github.com/citrix/citrix-adc-ansible-modules
# Creates an ldaps load balanced configuration including custom monitor.

- hosts: ctxadc
  gather_facts: false

  collections:
    - citrix.adc


  tasks:
# AH ldaps service  
    - name: setup ldaps monitor
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        monitorname: mon_ldaps.xalderhey.com
        type: LDAP
        interval: 15
        resptimeout: 5
        filter: cn=Builtin
        basedn: "{{ ldaps_basedn }}"
        binddn: "{{ ldaps_binddn }}"
        password: "{{ ldaps_bindpass }}"
        secure: yes
        
    - name: Setup ldaps service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: svcgrp_ldaps.xalderhey.com_636
        servicetype: TCP
        servicemembers:
            mode: exact
            attributes:
              - ip: "{{ ldap_svc1_ip }}"
                port: 636
              - ip: "{{ ldap_svc2_ip }}"
                port: 636

        monitor_bindings:
            mode: exact
            attributes:
              - monitor_name: mon_ldaps.xalderhey.com


    - name: Create vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: vsrv_ldaps.xalderhey.com_636
        servicetype: TCP
        persistencetype: SOURCEIP
        timeout: 12
        ipv46: "{{ ldapvs_ip }}"
        port: 636
        servicegroupbindings:
            - servicegroupname: svcgrp_ldaps.xalderhey.com_636

# AH ldaps service  
    - name: setup ldaps monitor
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        monitorname: mon_ldaps.xctc.ctc.nhs.uk
        type: LDAP
        interval: 15
        resptimeout: 5
        filter: cn=Builtin
        basedn: "{{ ldaps2_basedn }}"
        binddn: "{{ ldaps2_binddn }}"
        password: "{{ ldaps2_bindpass }}"
        secure: yes
        
    - name: Setup ldaps service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: svcgrp_ldaps.xctc.ctc.nhs.uk_636
        servicetype: TCP
        servicemembers:
            mode: exact
            attributes:
              - ip: "{{ ldap2_svc1_ip }}"
                port: 636
              - ip: "{{ ldap2_svc2_ip }}"
                port: 636

        monitor_bindings:
            mode: exact
            attributes:
              - monitor_name: mon_ldaps.xctc.ctc.nhs.uk


    - name: Create vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: vsrv_ldaps.xctc.ctc.nhs.uk_636
        servicetype: TCP
        persistencetype: SOURCEIP
        timeout: 12
        ipv46: "{{ ldap2vs_ip }}"
        port: 636
        servicegroupbindings:
            - servicegroupname: svcgrp_ldaps.xctc.ctc.nhs.uk_636

            
# storefront service  
    - name: setup storefront monitor
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        monitorname: mon_storefront
        type: STOREFRONT
        storename: "{{ storefront_name }}"
        storefrontacctservice: yes
        secure: yes
        
    - name: Setup storefront service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: svcgrp_storefront_443
        servicetype: SSL
        cip: enabled
        cipheader: X-Forwarded-For
        servicemembers:
            mode: exact
            attributes:
              - ip: "{{ storefront_svc1_ip }}"
                port: 443
              - ip: "{{ storefront_svc2_ip }}"
                port: 443

        monitor_bindings:
            mode: exact
            attributes:
              - monitor_name: mon_storefront

    - name: Create storefront vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: vsrv_storefront_443
        servicetype: SSL
        persistencetype: SOURCEIP
        lbmethod: ROUNDROBIN
        ssl_certkey: "{{ storefront_sslcert }}"
        timeout: 12
        ipv46: "{{ storefrontvs_ip }}"
        port: 443
        servicegroupbindings:
            - servicegroupname: svcgrp_storefront_443


# director service  
        
    - name: Setup director service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: svcgrp_director_443
        servicetype: SSL
        servicemembers:
            mode: exact
            attributes:
              - ip: "{{ director_svc1_ip }}"
                port: 443
              - ip: "{{ director_svc2_ip }}"
                port: 443

        monitor_bindings:
            mode: exact
            attributes:
              - monitor_name: https

    - name: Create director vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ ansible_host }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: vsrv_director_443
        servicetype: SSL
        persistencetype: SOURCEIP
        lbmethod: ROUNDROBIN
        ssl_certkey: "{{ director_sslcert }}"
        timeout: 12
        ipv46: "{{ directorvs_ip }}"
        port: 443
        servicegroupbindings:
            - servicegroupname: svcgrp_director_443

