- hosts: localhost
  vars_prompt:
    - name: vmname
      prompt: Please run with name of vm to be generated - eg ansible-playbook ctximagesealing.yaml -i ctxinventory.yaml -e vmname=rbs-ctxapp13 -vvv
      private: no
  tasks:
    - name: Add host to group ctxappws2019
      add_host:
        name: "{{ vmname }}"
        groups: ctxappws2019

- hosts: vsphere
  gather_facts: false
  tasks:
    - name: Power On
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ esxusername }}"
        password: "{{ esxpassword }}"
        validate_certs: False
        name: "{{ vmname }}"
        datacenter: "{{ esxdatacenter }} "
        folder: "{{ esxfolder }}"
        state: poweredon
        cluster: "{{ esxcluster }}" 

#update the image

- hosts: ctxappws2019
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: Wait 30 seconds, but only start checking after 10 seconds
    wait_for_connection:
      delay: 10
      timeout: 30
  - name: run sealing script
    win_shell: cmd /c "c:\masters\scripts\script-xendesktop-gold-image-sealing.cmd"
    ignore_errors: yes
    

#power down, snapshot
- hosts: vsphere
  gather_facts: false

  tasks:
    - name: Shutdown Guest OS
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ esxusername }}"
        password: "{{ esxpassword }}"
        validate_certs: False
        name: "{{ vmname }}"
        datacenter: "{{ esxdatacenter }} "
        state: shutdownguest
        cluster: "{{ esxcluster }}"
