---
- name: start VM
  hosts: vsphere
  gather_facts: no
  vars_prompt:
    - name: vmname
      prompt: What is the name of the VM?
      private: no
 
  tasks:
    - name: Power On
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ esxusername }}"
        password: "{{ esxpassword }}"
        validate_certs: False
        name: "{{ vmname }}"
        datacenter: "{{ esxdatacenter }}"
        state: poweredon
